name: Publish to PyPI

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check tag format
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if ! [[ $TAG_NAME =~ ^[0-9]+(\.[0-9]+){2}$ ]]; then
            echo "Tag $TAG_NAME does not match the version pattern. Skipping."
            exit 78
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          pip install setuptools wheel twine

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
